### ISSUE TITLE
Citizens integration

### ISSUE THREAD

**Issue by masterhacka** [promcteam/genesis#67]
Hi there,

since updating to genesis the current citizens integrations plugin won't work anymore.

Is there any way to integrate citizens directly to genesis?

**Comment by goflishMC** [comment]
> Hi there,
> 
> since updating to genesis the current citizens integrations plugin won't work anymore.
> 
> Is there any way to integrate citizens directly to genesis?

can you try selecting an npc, then type /npc command, you don't need a plugin to open shops, just add the command to the NPC

**Comment by masterhacka** [comment]
This is working fine. Thank you very much!
